services:
  postgresdb:
    image: postgres:17.2
    container_name: mn_postgresdb
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - pg_data_minos_reports:/var/lib/postgresql/data
      - ./postgres-initdb:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=minos
      - POSTGRES_USER=minos
      - POSTGRES_PASSWORD=minospass
  minosreports_api:
    build:
      dockerfile: Dockerfile-api
      context: ..
    volumes:
      - ../api/src/minosreports:/usr/local/lib/python3.12/site-packages/minosreports
    command:
      - uvicorn
      - minosreports.api:app
      - --host
      - "0.0.0.0"
      - --port
      - "80"
      - --reload
      - --reload-dir
      - /usr/local/lib/python3.12/site-packages/minosreports
    ports:
      - 127.0.0.1:8000:80
    environment:
      - POSTGRES_URI=postgresql+psycopg://minos:minospass@postgresdb:5432/minos
      - CF_POLICY_AUD=xxxxx
      - CF_TEAM_DOMAIN=https://xxxx.cloudflareaccess.com
      - SUPERVISOR_MAILS=xxxx1@acme.com
      - DLUS_MAILS=xxxx2@acme.com
      - API_ROOT_PATH=/api
    depends_on:
      - postgresdb
  minosreports_ui_dev:
    build:
      dockerfile: dev/minosreports_ui_dev/Dockerfile
      context: ..
    volumes:
      - ../ui/src:/app/src
      - ./config_dev.json:/app/public/config.json
    depends_on:
      - minosreports_api
  minosreports_ui_prod:
    build:
      dockerfile: Dockerfile-ui
      context: ..
    volumes:
      - ./config_prod.json:/app/public/config.json
    depends_on:
      - minosreports_api
  caddy_dev:
    image: caddy:latest
    ports:
      - 127.0.0.1:8001:80
    volumes:
      - ./Caddyfile_dev:/etc/caddy/Caddyfile
    depends_on:
      - minosreports_api
      - minosreports_ui_dev
  caddy_prod:
    image: caddy:latest
    ports:
      - 127.0.0.1:8002:80
    volumes:
      - ./Caddyfile_prod:/etc/caddy/Caddyfile
    depends_on:
      - minosreports_api
      - minosreports_ui_prod

volumes:
  pg_data_minos_reports:
