"""add station kind

Revision ID: 3153a01b2941
Revises: 644a6aca09e0
Create Date: 2025-04-25 05:27:23.422117

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3153a01b2941"
down_revision: str | None = "644a6aca09e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "station_kind",
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("label", name=op.f("pk_station_kind")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("station_kind")
    # ### end Alembic commands ###
