"""add food restrict to volunteers

Revision ID: 4af09bee8e75
Revises: b1c0eca737ad
Create Date: 2025-03-13 21:25:25.636777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4af09bee8e75"
down_revision: str | None = "b1c0eca737ad"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "volunteer",
        sa.Column("food_restrictions", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volunteer", "food_restrictions")
    # ### end Alembic commands ###
