"""add volunteer status

Revision ID: 4dd480915a98
Revises: 3153a01b2941
Create Date: 2025-05-08 21:22:16.389666

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4dd480915a98"
down_revision: str | None = "3153a01b2941"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteer_status",
        sa.Column("nivol", sa.String(), nullable=False),
        sa.Column("arrived", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("nivol", name=op.f("pk_volunteer_status")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("volunteer_status")
    # ### end Alembic commands ###
