"""change datetime column

Revision ID: 7b5ee2b93cde
Revises: be5106991260
Create Date: 2025-02-18 21:33:38.844579

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7b5ee2b93cde"
down_revision: str | None = "be5106991260"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("shift", sa.Column("start_date_time", sa.DateTime(), nullable=False))
    op.add_column("shift", sa.Column("end_date_time", sa.DateTime(), nullable=False))
    op.drop_index("ix_shift_endDateTime", table_name="shift")
    op.drop_index("ix_shift_startDateTime", table_name="shift")
    op.create_index(
        op.f("ix_shift_end_date_time"), "shift", ["end_date_time"], unique=False
    )
    op.create_index(
        op.f("ix_shift_start_date_time"), "shift", ["start_date_time"], unique=False
    )
    op.drop_column("shift", "endDateTime")
    op.drop_column("shift", "startDateTime")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shift",
        sa.Column(
            "startDateTime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "shift",
        sa.Column(
            "endDateTime", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.drop_index(op.f("ix_shift_start_date_time"), table_name="shift")
    op.drop_index(op.f("ix_shift_end_date_time"), table_name="shift")
    op.create_index("ix_shift_startDateTime", "shift", ["startDateTime"], unique=False)
    op.create_index("ix_shift_endDateTime", "shift", ["endDateTime"], unique=False)
    op.drop_column("shift", "end_date_time")
    op.drop_column("shift", "start_date_time")
    # ### end Alembic commands ###
