"""enrich volunteer data further

Revision ID: a5c9c17127de
Revises: 6f231de78a88
Create Date: 2025-02-24 21:57:14.406571

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a5c9c17127de"
down_revision: str | None = "6f231de78a88"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("volunteer", sa.Column("nivol", sa.String(), nullable=True))
    op.add_column("volunteer", sa.Column("dt", sa.String(), nullable=True))
    op.add_column("volunteer", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column("volunteer", sa.Column("email", sa.String(), nullable=True))
    op.add_column(
        "volunteer", sa.Column("incoming_date_time", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "volunteer",
        sa.Column("incoming_transportation_system", sa.String(), nullable=True),
    )
    op.add_column(
        "volunteer", sa.Column("incoming_train_station", sa.String(), nullable=True)
    )
    op.add_column(
        "volunteer", sa.Column("outgoing_date_time", sa.DateTime(), nullable=True)
    )
    op.add_column(
        "volunteer",
        sa.Column("outgoing_transportation_system", sa.String(), nullable=True),
    )
    op.add_column(
        "volunteer", sa.Column("outgoing_train_station", sa.String(), nullable=True)
    )
    op.add_column(
        "volunteer", sa.Column("crf_transportation_type", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volunteer", "crf_transportation_type")
    op.drop_column("volunteer", "outgoing_train_station")
    op.drop_column("volunteer", "outgoing_transportation_system")
    op.drop_column("volunteer", "outgoing_date_time")
    op.drop_column("volunteer", "incoming_train_station")
    op.drop_column("volunteer", "incoming_transportation_system")
    op.drop_column("volunteer", "incoming_date_time")
    op.drop_column("volunteer", "email")
    op.drop_column("volunteer", "phone_number")
    op.drop_column("volunteer", "dt")
    op.drop_column("volunteer", "nivol")
    # ### end Alembic commands ###
