"""add mission_restrict to volunteers

Revision ID: b1c0eca737ad
Revises: a5c9c17127de
Create Date: 2025-03-13 20:50:18.371477

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b1c0eca737ad"
down_revision: str | None = "a5c9c17127de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "volunteer",
        sa.Column("mission_restrictions", postgresql.ARRAY(sa.String()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volunteer", "mission_restrictions")
    # ### end Alembic commands ###
