name: Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and deploy

    environment: publish
    runs-on: ubuntu-24.04

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Build and publish Docker Image for UI
        uses: openzim/docker-publish-action@v10
        with:
          image-name: ploumpouloum/minos-reports-ui
          on-master: latest
          restrict-to: ploumpouloum/minos-reports
          registries: ghcr.io
          dockerfile: Dockerfile-ui
          # prettier-ignore
          credentials:
            GHCRIO_USERNAME=${{ vars.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}

      - name: Build and publish Docker Image for API
        uses: openzim/docker-publish-action@v10
        with:
          image-name: ploumpouloum/minos-reports-api
          on-master: latest
          restrict-to: ploumpouloum/minos-reports
          registries: ghcr.io
          dockerfile: Dockerfile-api
          # prettier-ignore
          credentials:
            GHCRIO_USERNAME=${{ vars.GHCR_USERNAME }}
            GHCRIO_TOKEN=${{ secrets.GHCR_TOKEN }}
