name: QA

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  check-api-qa:
    runs-on: ubuntu-24.04

    steps:
      - name: Retrieve source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: api/pyproject.toml
          architecture: x64

      - name: Install dependencies
        working-directory: api
        run: |
          pip install -U pip
          pip install -e .[lint,check,scripts,test]

      - name: Check black formatting
        working-directory: api
        run: inv lint-black

      - name: Check ruff
        working-directory: api
        run: inv lint-ruff

      - name: Check pyright
        working-directory: api
        run: inv check-pyright

  check-ui-qa:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ui/.node-version

      - name: Install JS dependencies
        working-directory: ui
        run: |
          yarn install

      - name: Check prettier
        working-directory: ui
        run: |
          yarn format

      - name: Check eslint
        working-directory: ui
        run: |
          yarn lint

      - name: Check Typescript typing
        working-directory: ui
        run: |
          yarn type-check
