"""create initial tables

Revision ID: 767093e9ae24
Revises:
Create Date: 2025-01-25 21:01:31.960922

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "767093e9ae24"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp";')
    op.create_table(
        "assignment",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("role", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assignment")),
    )
    op.create_table(
        "station",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("label", sa.String(), nullable=False),
        sa.Column("startDateTime", sa.DateTime(), nullable=False),
        sa.Column("endDateTime", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_station")),
    )
    op.create_table(
        "volunteer",
        sa.Column(
            "id",
            sa.Uuid(),
            server_default=sa.text("uuid_generate_v4()"),
            nullable=False,
        ),
        sa.Column("firstname", sa.String(), nullable=False),
        sa.Column("lastname", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_volunteer")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("volunteer")
    op.drop_table("station")
    op.drop_table("assignment")
    # ### end Alembic commands ###
